services:
  etcd:
    image: quay.io/coreos/etcd:${ETCD_VERSION}
    container_name: etcd # name of the container
    ports:
      - "2379:2379" # client url for other services to connect
      - "2380:2380" # peer url for clustering etcd nodes
    command: >
      etcd --name ${ETCD_NAME}
           --advertise-client-urls ${ETCD_ADVERTISE_CLIENT_URLS}
           --listen-client-urls ${ETCD_LISTEN_CLIENT_URLS}
           --listen-peer-urls ${ETCD_LISTEN_PEER_URLS}
           --data-dir ${ETCD_DATA_DIR}
           --auto-compaction-retention ${ETCD_AUTO_COMPACTION_RETENTION}
           --snapshot-count ${ETCD_SNAPSHOT_COUNT}
    volumes:
      - ./vtdataroot/etcd-data:/etcd-data:rw
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 10s
      timeout: 5s
      retries: 3

  vtctld:
    image: vitess/lite:${VITESS_VERSION}
    platform: linux/amd64
    container_name: vtctld
    depends_on:
      - etcd
    command: >
      sh -c '
        echo "Waiting for etcd to be healthy...";
        until wget -qO- http://etcd:2379/health | grep -q "true"; do
          sleep 2;
        done;
        echo "etcd is healthy, starting vtctld...";
        exec /vt/bin/vtctld \
          --config-file-not-found-handling=ignore \
          --topo_implementation ${VTCTLD_TOPO_IMPL} \
          --topo_global_server_address ${VTCTLD_TOPO_GLOBAL_ADDR} \
          --topo_global_root ${VTCTLD_TOPO_GLOBAL_ROOT} \
          --cell ${VTCTLD_CELL} \
          --service_map ${VTCTLD_SERVICE_MAP} \
          --backup_storage_implementation ${VTCTLD_BACKUP_STORAGE_IMPL} \
          --log_dir ${VTCTLD_BACKUP_STORAGE_IMPL}/tmp \
          --file_backup_storage_root ${VTCTLD_FILE_BACKUP_ROOT} \
          --grpc_bind_address=0.0.0.0 \
          --port 15000 \
          --grpc_port 15999 \
          --pprof-http \
          --logtostderr=${VTCTLD_LOGTOSTDERR}
      '
    ports:
      - "15000:15000"
      - "15999:15999"
    volumes:
      - ./vtctld-backups:/vt/vtdataroot/backups:rw
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://vtctld:15000/debug/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  vtctldclient:
    image: vitess/lite:${VITESS_VERSION}
    platform: linux/amd64
    container_name: vtctldclient
    depends_on:
      - vtctld
    command: >
      sh -c '
        etcdctl --endpoints=http://etcd:2379 put /vitess/zone1/ ""; \
        /vt/bin/vtctldclient AddCellInfo --server vtctld:15999 --root /vitess/zone1 --server-address etcd:2379 ${VTCTLD_CELL}; \
        /vt/bin/vtctldclient CreateKeyspace --server vtctld:15999 --durability-policy=semi_sync ${VTTABLET_KEYSPACE}; \
      '
    # TODO: vtctlclient ApplySchema -sql-file schema.sql your_keyspace
      
  vttablet0:
    image: vitess/lite:${VITESS_VERSION}
    container_name: vttablet0
    platform: linux/amd64
    depends_on:
      shard0:
        condition: service_healthy
      vtctldclient:
        condition: service_started
    command: >
      sh -c '
        until /vt/bin/vtctldclient GetCellInfo --server vtctld:15999 ${VTCTLD_CELL} \
          && /vt/bin/vtctldclient GetKeyspace --server vtctld:15999 ${VTTABLET_KEYSPACE}; do
            echo "Waiting for CellInfo and Keyspace..."
            sleep 2
        done
        echo "FOUND CellInfo..."
        exec /vt/bin/vttablet \
          --config-file-not-found-handling=ignore \
          --log_dir /vtdataroot/vttablet/logs \
          --topo_implementation ${VTCTLD_TOPO_IMPL} \
          --topo_global_root ${VTCTLD_TOPO_GLOBAL_ROOT} \
          --topo_global_server_address etcd:2379 \
          --init_db_name_override=cmms \
          --init_keyspace ${VTTABLET_KEYSPACE} \
          --init_shard ${VTTABLET_SHARD} \
          --tablet-path ${VTCTLD_CELL}-100 \
          --tablet_hostname= '' \
          --port 15100 \
          --grpc_port 16100 \
          --db_port 3306 \
          --db_app_user root \
          --db_app_password root \
          --db_host shard0 \
          --db-credentials-file=/vt/creds.json \
          --init_tablet_type replica \
          --service_map ${VTTABLET_SERVICE_MAP} \
          --pprof-http 
        '
    ports:
      - "15100:15100"
      - "16100:16100"
    healthcheck:
      interval: 30s
      retries: 15
      test: ["CMD-SHELL", "curl -s --fail --show-error vttablet0:15100/debug/health"]
      timeout: 10s
    volumes:
      - ./creds.json:/vt/creds.json
      - ./vtdataroot/vttablet0-data:/vtdataroot:rw
    restart: unless-stopped

  vttablet1:
    image: vitess/lite:${VITESS_VERSION}
    container_name: vttablet1
    platform: linux/amd64
    depends_on:
      shard1:
        condition: service_healthy
      vtctldclient:
        condition: service_started
    command: >
      sh -c '
        until /vt/bin/vtctldclient GetCellInfo --server vtctld:15999 ${VTCTLD_CELL} \
          && /vt/bin/vtctldclient GetKeyspace --server vtctld:15999 ${VTTABLET_KEYSPACE}; do
            echo "Waiting for CellInfo and Keyspace..."
            sleep 2
        done
        echo "FOUND CellInfo..."
        exec /vt/bin/vttablet \
          --config-file-not-found-handling=ignore \
          --log_dir /vtdataroot/vttablet/logs \
          --topo_implementation ${VTCTLD_TOPO_IMPL} \
          --topo_global_root ${VTCTLD_TOPO_GLOBAL_ROOT} \
          --topo_global_server_address etcd:2379 \
          --init_db_name_override=cmms \
          --init_keyspace ${VTTABLET_KEYSPACE} \
          --init_shard ${VTTABLET_SHARD} \
          --tablet-path ${VTCTLD_CELL}-101 \
          --tablet_hostname='' \
          --port 15101 \
          --grpc_port 16101 \
          --db_port 3306 \
          --db_app_user root \
          --db_app_password root \
          --db_host shard1 \
          --db-credentials-file=/vt/creds.json \
          --init_tablet_type replica \
          --service_map ${VTTABLET_SERVICE_MAP} \
          --pprof-http 
        '
    ports:
      - "15101:15101"
      - "16101:16101"
    healthcheck:
      interval: 30s
      retries: 15
      test: ["CMD-SHELL", "curl -s --fail --show-error vttablet1:15101/debug/health"]
      timeout: 10s
    volumes:
      - ./creds.json:/vt/creds.json
      - ./vtdataroot/vttablet1-data:/vtdataroot:rw
    # restart: unless-stopped

  vtgate:
    image: vitess/lite:${VITESS_VERSION}
    platform: linux/amd64
    container_name: vtgate
    depends_on:
      vtctld:
        condition: service_healthy
      vttablet0:
        condition: service_started
      vttablet1:
        condition: service_started
    command: >
      sh -c '
        exec /vt/bin/vtgate \
          --topo_implementation=${VTCTLD_TOPO_IMPL} \
          --topo_global_server_address=etcd:2379 \
          --topo_global_root=${VTCTLD_TOPO_GLOBAL_ROOT} \
          --cell=${VTCTLD_CELL} \
          --cells_to_watch=${VTCTLD_CELL} \
          --tablet_types_to_wait=REPLICA,PRIMARY \
          --tablet_protocol=grpc \
          --port=15001 \
          --grpc_port=15991 \
          --mysql_server_port=15306 \
          --mysql_auth_server_impl=static \
          --mysql_auth_server_static_file=/vt/config/mysql_auth_server_static.json \
          --service_map=grpc-queryservice,grpc-tabletmanager,grpc-updatestream,grpc-vtgateservice \
          --logtostderr=true
      '
    ports:
      - "15001:15001"  # HTTP web UI
      - "15991:15991"  # gRPC port
      - "15306:15306"  # MySQL protocol
    volumes:
      - ./mysql_auth_server.json:/vt/config/mysql_auth_server_static.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15001/debug/status"]
      interval: 10s
      timeout: 5s
      retries: 5

  shard0:
    image: mysql:8.0.43
    container_name: shard0
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0 --server-id=100
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    healthcheck:
      retries: 10
      test: ["CMD", "mysql", "-uroot", "-proot", "-e", "SHOW DATABASES;"]
      timeout: 10s
    ports:
      - "13316:3306"
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/scripts/:/docker-entrypoint-initdb.d/
  
  shard1:
    image: mysql:8.0.43
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0 --server-id=101 
    container_name: shard1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    healthcheck:
      retries: 10
      test: ["CMD", "mysql", "-uroot", "-proot", "-e", "SHOW DATABASES;"]
      timeout: 10s
    ports:
      - "13326:3306"
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/scripts/:/docker-entrypoint-initdb.d/

  vtorc:
    platform: linux/amd64
    command: >
      sh -c '
        exec /vt/bin/vtorc \
          --topo_implementation=${VTCTLD_TOPO_IMPL} \
          --topo_global_server_address=etcd:2379 \
          --topo_global_root=${VTCTLD_TOPO_GLOBAL_ROOT} \
          --log_dir $VTDATAROOT/tmp \
          --port 8080 \
          --config-file=/vtorc.json
      '
    depends_on:
      vtctld:
        condition: service_healthy
      vtctldclient:
        condition: service_started
    image: vitess/lite:v20.0.8
    ports:
    - 13000:8080
    volumes:
    - ./vtorc.json:/vtorc.json