-- Constraint: qrtz_blob_triggers_ibfk_1
CREATE TRIGGER `trg_qrtz_blob_triggers_ibfk_1_restrict_del` BEFORE DELETE ON `QRTZ_TRIGGERS`
FOR EACH ROW
BEGIN
    IF EXISTS (SELECT 1 FROM `QRTZ_BLOB_TRIGGERS` WHERE `SCHED_NAME` = OLD.`SCHED_NAME` AND `TRIGGER_NAME` = OLD.`TRIGGER_NAME` AND `TRIGGER_GROUP` = OLD.`TRIGGER_GROUP` LIMIT 1) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'RESTRICT: Child record exists in QRTZ_BLOB_TRIGGERS';
    END IF;
END;